       - name: Create Pull Request
         if: steps.git-check.outputs.changed == 'true'
         uses: peter-evans/create-pull-request@v5
         with:
           commit-message: "chore: daily dependency update"
           title: 'Daily Dependency Update'
           body: |
             ## :robot: Automated Dependency Update

             This pull request was created automatically by the daily dependency update workflow.

             **Summary of changes:**
             - Updated dependencies using `npm update`.
             - Changes detected in `package.json` and/or `package-lock.json`.

             **Files changed:**
             - `package.json`
             - `package-lock.json`

             **Checklist:**
             - [ ] Review the dependency changes below
             - [ ] Run the application and verify it works as expected
             - [ ] Check for any breaking changes in updated packages

             **Workflow run:** `${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}`

             _Automated PR generated at: `${{ github.event.head_commit.timestamp || github.run_started_at }}`_

             ---
             > Please merge if all checks pass and the application works as expected.
           branch: chore/deps-update-${{ env.BRANCH_TIMESTAMP }}